spring.application.name=procesamientoia

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=alumno
spring.datasource.password=Alumno123!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# =========================
# CONFIGURACION PROCESAMIENTO
# =========================

openai.api-key=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

openai.model=gpt-5.5

openai.url=https://api.openai.com/v1/responses

openai.intervalo-ms=1000

openai.max-reintentos=3

openai.espera-reintento-ms=2000


# =========================
# CONFIGURACION PROCESAMIENTO
# =========================

procesamiento.numero-hilos=4